[workspace]
authors = ["a-chahal <aaranchahal09@gmail.com>"]
channels = ["conda-forge"]
name = "pains_brenk"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rdkit = ">=2026.3.4,<2027"
